Algoritmo "entrada-dados"

Var

nome : caractere
idade : inteiro
salario1, salario2 : real

Inicio

escreva("Digite seu nome: ")
leia(nome)
escreva("Digite sua idade: ")
leia(idade)
escreval("Digite seus ultimos dois salários: ")
leia(salario1)
leia(salario2)

escreval
escreval("DADOS DIGITADOS: ")
escreval("Nome: ", nome, ", idade: ", idade, ", ultimos dois salários: ", salario1:8:2, " e ", salario2:8:2)

Fimalgoritmo